name: Generate Java Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: corretto

      - name: Build with Maven
        run: mvn clean install

      - name: Generate Javadocs
        run: mvn javadoc:javadoc

      # Publishes Javadocs to GitHub Pages by pushing to `gh-pages` branch
      - name: Deploy Javadocs to GitHub Pages
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          mvn scm-publish:publish-scm
