name: github-release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Create GitHub release of following tag
        required: true
        type: string
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:

      - name: Create GitHub release
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/spotify/github-java-client/releases \
            -d '{"tag_name":"${{ inputs.tag }}","target_commitish":"master","draft":false,"prerelease":false,"generate_release_notes":true}'